spring.application.name=Taskmanagement

spring.datasource.url=jdbc:mysql://localhost:3306/taskmanagementdb
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}